# Generated by Django 3.0.4 on 2020-04-07 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('type', models.CharField(choices=[('phone', 'Phone'), ('email', 'E-mail'), ('other', 'Other')], max_length=50, verbose_name='Тип контакта')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Гарантия',
                'verbose_name_plural': 'Гарантии',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='BuhPro', max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Описание')),
                ('text', models.TextField(default='', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Стартовая страница',
                'verbose_name_plural': 'Стартовые страницы',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('poster', models.ImageField(height_field=225, upload_to='', verbose_name='Постер')),
                ('text', models.TextField(verbose_name='Текст')),
                ('url', models.SlugField(verbose_name='url')),
                ('publish', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='SiteWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BuhPro', max_length=100, verbose_name='Название компании')),
                ('show_about', models.BooleanField(default=True, verbose_name='Показывать блок About')),
                ('about', models.CharField(default='Лучшие бухгалтерские услуги в Санкт-Петербурге.', max_length=500, verbose_name='Заголовок')),
                ('footer_text', models.CharField(default='По всем вопросам обращайтесь по телефону или другим контактам', max_length=500, verbose_name='Текст снизу сайта')),
                ('footer_link', models.CharField(default='Контакты', max_length=500, verbose_name='Ссылка снизу сайта')),
            ],
            options={
                'verbose_name': 'Редактор сайта',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 4, 7, 15, 5, 29, 20617, tzinfo=utc), verbose_name='Дата')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buh.Service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запрос услуги',
                'verbose_name_plural': 'Запрос услуг',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя изображения')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buh.Service')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
